<div id="nav">
{foreach $nav as $_}
    <a href="{link Show:, $_->getNiceName()}">{$_->getName()}</a> »
{/foreach}
</div>
<h1 id="product-header">{$product->getName()}</h1>

<div class="row" id="product">
    <div class="column grid-4 side">
        <div class="image">
            {if $product->getPicture() !== NULL}
                <img src="{=Environment::expand('%mediaBaseUri%/' . $product->getPicture()->getFile())}" alt="{$product->getName()}">
            {else}
                <img src="{=Environment::expand('%themeBaseUri%/img/nopicture-big.png')}" alt="{$product->getName()}">
            {/if}
        </div>
        <div class="info">
            <div class="price">{$product->getPrice()}&thinsp;{=Environment::expand('%currency%')}</div>
            {if $product->getAvailability()}
            <div class="availability">{$product->getAvailability()->getName()}</div>
            {/if}
            <div class="cart">
                <p>{=__('%d pcs of this product in cart', isset($side->cart->products[$product->getId()]) ? $side->cart->products[$product->getId()] : 0)}</p>
                <p><form method="post" action="{link Order:add}">
                    <input type="hidden" name="product_id" value="{$product->getId()}">
                    <input type="text" name="amount" value="1" size="1">&thinsp;{=__('pcs')}
                    <input type="submit" value="{=__('into the cart')}">
                </form></p>
                <p>{if isset($side->cart->products[$product->getId()]) && $side->cart->products[$product->getId()] > 0}
                <form method="post" action="{link Order:delete}">
                        <input type="hidden" name="product_id" value="{$product->getId()}">
                        <input type="text" name="amount" value="{$side->cart->products[$product->getId()]}" size="1">&thinsp;{=__('pcs')}
                        <input type="submit" value="{=__('out of the cart')}">
                </form>{/if}</p>
            </div>
        </div>
    </div>
    <div class="column grid-5 description">
    {if $product->getMetaDescription() != ''}
        {!$product->getMetaDescription()|texy}
    {else}
        {!$product->getName()|texy}
    {/if}
    {!$product->getDescription()|texy}
    </div>
</div>