<h1>{$category->getName()}</h1>
{!$category->getDescription()|texy}

{if !empty($subcategories)}
    <ul>
    {foreach $subcategories as $_}
        <li><a href="{link default, $_->getNiceName()}">{$_->getName()}</a></li>
    {/foreach}
    </ul>
{/if}
{if $category->getPicture()}
    <img src="{=Environment::expand('%mediaBaseUri%/' . $category->getPicture()->getFile())}" alt="{$category->getName()}" style="float: right; margin: 10px;">
{/if}
<hr style="clear: both;">
{include '@products.phtml', 'products' => $products}

